# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['order_index', '-id'], 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontacts',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical контакт'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='_contacts_index',
        ),
        migrations.RemoveField(
            model_name='historicalcontacts',
            name='_contacts_index',
        ),
        migrations.AddField(
            model_name='contacts',
            name='order_index',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='historicalcontacts',
            name='order_index',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Номера телефонов вводятся в произвольном формате через запятую', size=None, verbose_name='Номера телефонов служб'),
        ),
        migrations.AlterField(
            model_name='historicalcontacts',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Номера телефонов вводятся в произвольном формате через запятую', size=None, verbose_name='Номера телефонов служб'),
        ),
    ]
