# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171204_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['order_index', '-id'], 'permissions': (('can_edit_contacts', 'Может редактировать контакты'),), 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='order_index',
            field=models.IntegerField(default=100, verbose_name='Индекс для сортировки'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Номера телефонов вводятся в произвольном формате через запятую', size=None, verbose_name='Номера телефонов'),
        ),
        migrations.AlterField(
            model_name='historicalcontacts',
            name='order_index',
            field=models.IntegerField(default=100, verbose_name='Индекс для сортировки'),
        ),
        migrations.AlterField(
            model_name='historicalcontacts',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Номера телефонов вводятся в произвольном формате через запятую', size=None, verbose_name='Номера телефонов'),
        ),
    ]
