# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20171205_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='HistoricalContacts',
            new_name='HistoricalContact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id'], 'permissions': (('can_edit_contact', 'Может редактировать контакты'),), 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
