# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180216_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.Contact'),
        ),
    ]
