# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180216_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='обновлен'),
        ),
    ]
