# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-17 14:17
from __future__ import unicode_literals

from django.db import migrations


CONTACT_UPDATED_INDEX_NAME = 'historical_contact_updated_field'
CONTACT_UPDATED_UID_INDEX_NAME = 'historical_contact_updated_uid_fields'
COMMENT_UPDATED_INDEX_NAME = 'historical_comment_updated_field'
COMMENT_UPDATED_UID_INDEX_NAME = 'historical_comment_updated_uid_fields'



class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180605_1058'),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            CREATE INDEX {CONTACT_UPDATED_INDEX_NAME} ON 
            contacts_historicalcontact (updated);
            CREATE INDEX {CONTACT_UPDATED_UID_INDEX_NAME} ON 
            contacts_historicalcontact (updated, uid);
            
            CREATE INDEX {COMMENT_UPDATED_INDEX_NAME} ON 
            contacts_historicalcomment (updated);
            CREATE INDEX {COMMENT_UPDATED_UID_INDEX_NAME} ON 
            contacts_historicalcomment (updated, uid);
            """,
            reverse_sql=f"""
            DROP INDEX {CONTACT_UPDATED_INDEX_NAME};
            DROP INDEX {CONTACT_UPDATED_UID_INDEX_NAME};
            
            DROP INDEX {COMMENT_UPDATED_INDEX_NAME};
            DROP INDEX {COMMENT_UPDATED_UID_INDEX_NAME};
            """),
    ]
