# Generated by Django 2.1.2 on 2018-10-31 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_create_table_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='updated'),
        ),
    ]
