# Generated by Django 2.2.5 on 2019-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190418_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.IntegerField(choices=[(0, 'Неизвестный'), (1, 'Сотрудник'), (2, 'Подрядчик'), (3, 'Клиент')], default=0, verbose_name='Тип контакта'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='contact_type',
            field=models.IntegerField(choices=[(0, 'Неизвестный'), (1, 'Сотрудник'), (2, 'Подрядчик'), (3, 'Клиент')], default=0, verbose_name='Тип контакта'),
        ),
    ]
