# Generated by Django 2.1.7 on 2019-04-24 08:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190418_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=core.fields.NormalizedCharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=core.fields.NormalizedCharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=core.fields.NormalizedCharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=core.fields.NormalizedCharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
