# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscribe',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
