# Generated by Django 2.1.7 on 2019-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateState',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
