#!/usr/bin/env python
# coding=utf-8

from __future__ import unicode_literals
from __future__ import print_function

import os
import sys
from os.path import dirname, abspath, join

__author__ = 'pahaz'

GIT_IGNORE_FILE = b"""# auto generated by pahaz/django-project-stub
.idea
*.py[cod]

__data__*
_project_*/settings/local_settings.py
"""

README_FILE = b"""# PROJECT DOCS #
This project generated by https://github.com/pahaz/django-project-stub

# CONTRIBUTORS #

# CHANGELOG #

"""


###############
#             #
#  HELPERS    #
#             #
###############

def _get_random_string(length=32,
                       allowed_chars='abcdefghijklmnopqrstuvwxyz'
                                     'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
                                     '0123456789'):
    import random

    return ''.join([random.choice(allowed_chars) for _ in range(length)])


def _add_helpers_paths():
    if hasattr(_add_helpers_paths, "path_fixed"):
        return
    # insert stub root for import paths
    _path = join(abspath(dirname(__file__)), 'helpers')
    sys.path.insert(1, _path)
    setattr(_add_helpers_paths, "path_fixed", True)


###############
#             #
#    MAIN     #
#             #
###############

if __name__ == "__main__":
    _add_helpers_paths()

    from _settings import settings, root_join
    from lib import rm_file, rm_dir
    from mkfolders import make_all_required_dirs

    print("INITIALIZING PROJECT")

    print("GENERATE PRODUCTION SETTINGS `SECRET_KEY`")
    _secret = _get_random_string()
    _path = root_join("_project_", "settings", "production_settings.py")
    production_settings_file = open(_path, 'a')
    production_settings_file.write('\nSECRET_KEY = "{0}"\n'.format(_secret))
    production_settings_file.close()

    print("CLEANING STUB")
    rm_file(root_join('test.py'))

    print("RECREATE `.GITIGNORE` FILE")
    _path = root_join(".gitignore")
    git_ignore_file = open(_path, 'wb')
    git_ignore_file.write(GIT_IGNORE_FILE)
    git_ignore_file.close()

    print("RECREATE `README.md` FILE")
    _path = root_join("README.md")
    git_ignore_file = open(_path, 'wb')
    git_ignore_file.write(README_FILE)
    git_ignore_file.close()

    print("INIT DATA DIRS (__data__, tmp, media, collect_static)")
    make_all_required_dirs(settings)

    print("INIT NEW GIT REPOSITORY")
    rm_dir(root_join('.git'))
    os.system("git init")
    os.system("git add *")
    os.system('git commit -am "Init form pahaz/django-project-stub"')

    print("REMOVE SELF")
    os.remove(__file__)

    print("""INITED.

    NOW WE CAN USE:
     * python helpers/mkvirtualenv.py
    """)
