from __future__ import unicode_literals
from __future__ import print_function
import os
from os.path import dirname, join


###############
#             #
#  VARIABLES  #
#             #
###############

__author__ = 'pahaz'
BASE_DIR = dirname(__file__)

GIT_IGNORE_FILE = """
.idea
*.py[cod]

__data__*
_project_*/settings/local_settings.py
"""

README_FILE = """
# PROJECT DOCS #
This project generated by https://github.com/pahaz/django-project-stub

# CONTRIBUTORS #

# CHANGELOG #

"""


###############
#             #
#  HELPERS    #
#             #
###############

def _get_random_string(length=12,
                       allowed_chars='abcdefghijklmnopqrstuvwxyz'
                                     'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
                                     '0123456789'):
    import random

    return ''.join([random.choice(allowed_chars) for i in range(length)])


###############
#             #
#    MAIN     #
#             #
###############

if __name__ == "__main__":
    print("INITIALIZING PROJECT")

    print("GENERATE PRODUCTION SETTINGS `SECRET_KEY`")
    _secret = _get_random_string()
    _path = join(BASE_DIR, "_project_", "settings", "production_settings.py")
    production_settings_file = open(_path, 'a')
    production_settings_file.write('\nSECRET_KEY = "{0}"\n'.format(_secret))
    production_settings_file.close()

    print("RECREATE `.GITIGNORE` FILE")
    _path = join(BASE_DIR, ".gitignore")
    git_ignore_file = open(_path, 'w')
    git_ignore_file.write(GIT_IGNORE_FILE)
    git_ignore_file.close()

    print("RECREATE `README.md` FILE")
    _path = join(BASE_DIR, "README.md")
    git_ignore_file = open(_path, 'w')
    git_ignore_file.write(README_FILE)
    git_ignore_file.close()

    print("INIT NEW GIT REPOSITORY")
    os.rmdir(join(BASE_DIR, '.git'))
    os.system("git init")
    os.system("git add *")
    os.system('git commit -am "Init form pahaz/django-project-stub"')

    print("REMOVE SELF")
    os.remove(__path__)

    print("""INITED.
    NOW WE CAN ... TODO THIS!
""")
