# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 10:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='отправитель письма')),
                ('email_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='получатель письма'), size=None)),
                ('subject', models.CharField(blank=True, max_length=1024, null=True, verbose_name='тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='тело письма')),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, editable=False, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст ошибки')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
