# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0002_auto_20180528_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cors',
            options={'verbose_name': 'Разрешение на кросс-доменные запросы', 'verbose_name_plural': 'Разрешения на кросс-доменные запросы'},
        ),
        migrations.AlterModelOptions(
            name='historicalcors',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Разрешение на кросс-доменные запросы'},
        ),
    ]
