# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import pik.core.models.uided


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0003_auto_20180531_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalcors',
            name='id',
        ),
        migrations.AddField(
            model_name='cors',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cors',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='historicalcors',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcors',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cors',
            name='uid',
            field=models.UUIDField(default=pik.core.models.uided._new_uid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cors',
            name='version',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcors',
            name='uid',
            field=models.UUIDField(db_index=True, default=pik.core.models.uided._new_uid, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcors',
            name='version',
            field=models.IntegerField(editable=False),
        ),
    ]
