# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_replica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplica',
            name='deleted',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='contactreplica',
            name='deleted',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='commentreplica',
            name='version',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='contactreplica',
            name='version',
            field=models.IntegerField(editable=False),
        ),
    ]
