# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 20:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts_replica', '0002_auto_20180506_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCommentReplica',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Updated')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(editable=False)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts_replica.ContactReplica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical коментарий',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalContactReplica',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Updated')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('version', models.IntegerField(editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Номера телефонов вводятся в произвольном формате через запятую', size=None, verbose_name='Номера телефонов')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='E-mail адреса вводятся через запятую', size=None, verbose_name='E-mail адреса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical контакт',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
