# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import pik.core.models.uided


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_replica', '0003_historicalcommentreplica_historicalcontactreplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreplica',
            name='uid',
            field=models.UUIDField(default=pik.core.models.uided._new_uid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactreplica',
            name='uid',
            field=models.UUIDField(default=pik.core.models.uided._new_uid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcommentreplica',
            name='uid',
            field=models.UUIDField(db_index=True, default=pik.core.models.uided._new_uid, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcontactreplica',
            name='uid',
            field=models.UUIDField(db_index=True, default=pik.core.models.uided._new_uid, editable=False),
        ),
    ]
