# ########################################################### #
# This file is automatically generated. Please don't edit it! #
# ########################################################### #
# COMMAND: <hidden>

from django.contrib.postgres.fields import JSONField
from django.db import models


class BaseUser(models.Model):
    email = models.CharField(verbose_name='Email', editable=False, null=True, max_length=255)
    username = models.CharField(verbose_name='Username', editable=False, null=True, max_length=255)

    class Meta:
        abstract = True


class BaseHistoricalContact(models.Model):
    history_id = models.IntegerField(verbose_name='History id', editable=False, null=True)
    history_date = models.DateTimeField(verbose_name='History date', editable=False, null=True)
    history_change_reason = models.CharField(verbose_name='History change reason', editable=False, null=True, max_length=255)
    history_type = models.CharField(verbose_name='History type', editable=False, null=True, max_length=255)
    history_user_id = models.IntegerField(verbose_name='History user id', editable=False, null=True)
    history_user = JSONField(verbose_name='History user', editable=False, default=dict)
    uid = models.CharField(verbose_name='uid', primary_key=True, max_length=255)
    type = models.CharField(verbose_name='type', editable=False, null=True, max_length=255)
    version = models.CharField(verbose_name='version', editable=False, null=True, max_length=255)
    created = models.DateTimeField(verbose_name='Создан', editable=False, null=True)
    updated = models.DateTimeField(verbose_name='Updated', editable=False, null=True)
    name = models.CharField(verbose_name='Наименование', editable=False, null=True, max_length=255)
    phones = JSONField(verbose_name='Номера телефонов', editable=False, default=dict)
    emails = JSONField(verbose_name='E-mail адреса', editable=False, default=dict)
    order_index = models.IntegerField(verbose_name='Индекс для сортировки', editable=False, null=True)

    class Meta:
        abstract = True


class BaseContact(models.Model):
    uid = models.CharField(verbose_name='uid', primary_key=True, max_length=255)
    type = models.CharField(verbose_name='type', editable=False, null=True, max_length=255)
    version = models.CharField(verbose_name='version', editable=False, null=True, max_length=255)
    created = models.DateTimeField(verbose_name='Создан', editable=False, null=True)
    updated = models.DateTimeField(verbose_name='Updated', editable=False, null=True)
    name = models.CharField(verbose_name='Наименование', editable=False, null=True, max_length=255)
    phones = JSONField(verbose_name='Номера телефонов', editable=False, default=dict)
    emails = JSONField(verbose_name='E-mail адреса', editable=False, default=dict)
    order_index = models.IntegerField(verbose_name='Индекс для сортировки', editable=False, null=True)

    class Meta:
        abstract = True


class BaseHistoricalComment(models.Model):
    history_id = models.IntegerField(verbose_name='History id', editable=False, null=True)
    history_date = models.DateTimeField(verbose_name='History date', editable=False, null=True)
    history_change_reason = models.CharField(verbose_name='History change reason', editable=False, null=True, max_length=255)
    history_type = models.CharField(verbose_name='History type', editable=False, null=True, max_length=255)
    history_user_id = models.IntegerField(verbose_name='History user id', editable=False, null=True)
    history_user = JSONField(verbose_name='History user', editable=False, default=dict)
    uid = models.CharField(verbose_name='uid', primary_key=True, max_length=255)
    type = models.CharField(verbose_name='type', editable=False, null=True, max_length=255)
    version = models.CharField(verbose_name='version', editable=False, null=True, max_length=255)
    created = models.DateTimeField(verbose_name='Создан', editable=False, null=True)
    updated = models.DateTimeField(verbose_name='Updated', editable=False, null=True)
    user = models.IntegerField(verbose_name='User', editable=False, null=True)
    contact = JSONField(verbose_name='contact', editable=False, default=dict)
    message = models.CharField(verbose_name='Сообщение', editable=False, null=True, max_length=255)

    class Meta:
        abstract = True


class BaseComment(models.Model):
    uid = models.CharField(verbose_name='uid', primary_key=True, max_length=255)
    type = models.CharField(verbose_name='type', editable=False, null=True, max_length=255)
    version = models.CharField(verbose_name='version', editable=False, null=True, max_length=255)
    created = models.DateTimeField(verbose_name='Создан', editable=False, null=True)
    updated = models.DateTimeField(verbose_name='Updated', editable=False, null=True)
    user = models.IntegerField(verbose_name='User', editable=False, null=True)
    contact = JSONField(verbose_name='contact', editable=False, default=dict)
    message = models.CharField(verbose_name='Сообщение', editable=False, null=True, max_length=255)

    class Meta:
        abstract = True


